spring.application.name: api-gateway

server.port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: posts-service
          uri: lb://posts-service
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2

        - id: connections-service
          uri: lb://connections-service
          predicates:
            - Path=/api/v1/conenctions/**
          filters:
            - StripPrefix=2
